### ISSUE TITLE
Setup example (question)

### ISSUE THREAD

**Issue by nanjum30** [TheOrangeDots/servoy-amqpconsumers-plugin#1]
Hi Developer,

We are trying to setup the connection in Servoy but unable to connect successfully using properties tod.queuing. . Can you please provide sample to use tod.queuing properties in Servoy properties file or some other file.

Any guidance will be highly appreciated.

Thanks

**Comment by p-bakker** [comment]
Hi,

Tnx for your inquiry. A lot of examples and explanation is provided in the readme, so please provide more details on your setup, your config, what you have tried and what kind of behavior you're experiencing

**Comment by nanjum30** [comment]
Hi,

Thanks for the quick response.

We have reviewed the read me and placed following snippet in servoy.properties file but unable to observe message consumption:

tod.queueing.connection.host=localhost
tod.queueing.connection.user=guest
tod.queueing.connection.password=guest
tod.queueing.connection.port=5672
tod.queueing.consumer.autoack=true
tod.queueing.consumer.consumerTag=myConsumerTag1
tod.queueing.consumer.exclusive=true
tod.queueing.consumer.handler=rabbitmq_test\://scopes.amqpMessageHandling.consumeRPC
tod.queueing.consumer.nolocal=true
tod.queueing.consumer.queue=rpc
tod.queueing.queue.autodelete=true
tod.queueing.queue.channel=1
tod.queueing.queue.durable=true
tod.queueing.queue.exclusive=true
tod.queueing.queue.name=rpc
tod.queueing.exchange.channel=1
tod.queueing.exchange.durable=true
tod.queueing.exchange.name=rpc
tod.queueing.exchange.type=direct
tod.queueing.binding.exchange=rpc
tod.queueing.binding.queue=rpc
tod.queueing.binding.routingkey=myRpcRouting

Should we first create the channel, queue or exchange at RabbitMQ server by ourselves?

We are expecting to receive message on databroadcast so we can further handle as required.

Thanks

**Comment by p-bakker** [comment]
Could youtry the config below?
Channels, Queues and Exchanges should be automatically created by the plugin if they aren't already defined inside RMQ. 

```
tod.queueing.connection.host=localhost
tod.queueing.connection.user=guest
tod.queueing.connection.password=guest
tod.queueing.connection.port=5672

tod.queueing.exchange.1.durable=true
tod.queueing.exchange.1.name=rpc
tod.queueing.exchange.1.type=direct

tod.queueing.queue.1.autodelete=true
tod.queueing.queue.1.durable=true
tod.queueing.queue.1.exclusive=true
tod.queueing.queue.1.name=rpc

tod.queueing.binding.exchange=1
tod.queueing.binding.queue=1
tod.queueing.binding.routingkey=myRpcRouting

tod.queueing.consumer.autoack=true
tod.queueing.consumer.consumerTag=myConsumerTag1
tod.queueing.consumer.exclusive=true
tod.queueing.consumer.handler=rabbitmq_test://scopes.amqpMessageHandling.consumeRPC
tod.queueing.consumer.nolocal=true
tod.queueing.consumer.queue=1

```

**Comment by nanjum30** [comment]
Thanks for the config. Now, connection, queue & exchanges has been created as defined. But it is still not hitting the handler method defined as 'tod.queueing.consumer.handler=rabbitmq_test://scopes.amqpMessageHandling.consumeRPC'.

**Comment by p-bakker** [comment]
Ok, so I assume you have a solution called 'rabbitmq_test' containing a scope 'amqpMessageHandling' that has a method called 'consumeRPC' in it?

And that you're publishing messages to the 'rpc' exchange having 'myRpcRouting' as routing key?

Can you confirm on the RMQ side (for example via the UI provided by the [Management Plugin](https://www.rabbitmq.com/management.html)) that:
- the messages are being received by RMQ and routed to the defined queue? 
- that the the consumer is connected to queue?

**Comment by nanjum30** [comment]
Yes, we publish messages from RMQ Server UI, but these are not consumed as handler is not triggered. I guess we are facing issue with consumer that either consumer is not connected or is not responding.

**Comment by p-bakker** [comment]
With `RMQ Server UI` I assume the Management UI from the aforementioned Management Plugin? If so: check to see if the queue has a consumer andor whether the messages you publish are remaining in the queue

**Comment by nanjum30** [comment]
Yes, RMQ Server UI means to mention Management UI. When we try to publish message from UI, message count for Ready increases but no triggers on handler.
![image](https://user-images.githubusercontent.com/52948615/225294072-9b019cc4-eb40-44aa-9a01-68e6a9923ba2.png)
We can see binding of Default Exchange in queue:
![image](https://user-images.githubusercontent.com/52948615/225294328-2bddb12e-3f15-48ba-96e1-83d8b7cb33ba.png)

**Comment by p-bakker** [comment]
The screenshots seem to indicate there's no binding and also do not answer the question whether there is a consumer.

Could you try though with this as settings:
```
tod.queueing.connection.host=localhost
tod.queueing.connection.user=guest
tod.queueing.connection.password=guest
tod.queueing.connection.port=5672

tod.queueing.exchange.durable=true
tod.queueing.exchange.name=rpc
tod.queueing.exchange.type=direct

tod.queueing.queue.autodelete=true
tod.queueing.queue.durable=true
tod.queueing.queue.exclusive=true
tod.queueing.queue.name=rpc

tod.queueing.binding.routingkey=myRpcRouting

tod.queueing.consumer.autoack=true
tod.queueing.consumer.consumerTag=myConsumerTag1
tod.queueing.consumer.exclusive=true
tod.queueing.consumer.handler=rabbitmq_test://scopes.amqpMessageHandling.consumeRPC
tod.queueing.consumer.nolocal=true
```

**Comment by nanjum30** [comment]
Thanks for the help. Its now publishing messages sent from UI into servoy application.

**Comment by nanjum30** [comment]
Hi Paul,

Please suggest way to read the message published on databroadcast channel in handler method, which we have configured in servoy properties file, in order to read the information and utilize the data broadcast.

Thanks

**Comment by p-bakker** [comment]
I assume you mean Servoy's databroadcasting messages? Those are binary representations of internal classes of Servoy, you cannot decode them.

But, you shouldn't have to: if you're interested in acting on incoming databroadcasts, just as a onDataBroadcast event handler on your solution

**Comment by nanjum30** [comment]
Yes, we are referring to Servoy's databroadcast messages. And we need to consume it at Servoy side to take effect.

**Comment by p-bakker** [comment]
Servoy automatically processes databroadcast messages is you connect Servoy up to RabbitMQ as stated here: https://wiki.servoy.com/display/DOCS/AMQP+%28RabbitMQ%29+scaling+by+broadcasting+databroadcast+messages

**Comment by nanjum30** [comment]
Thanks for your guidance.
